export const SELECTED_FIELDS = new Map(
  Object.entries({
    'aiserver.v1.GetMeRequest': '*',
    'aiserver.v1.GetMeResponse': '*',
    'aiserver.v1.GetServerConfigResponse': ['agentUrlConfig'],
    'aiserver.v1.AvailableModelsRequest': '*',
    'aiserver.v1.AvailableModelsResponse': '*',
    'aiserver.v1.AvailableModelsResponse.AvailableModel': ['name', 'serverModelName', 'variants'],
    'aiserver.v1.AvailableModelsResponse.ModelVariantConfig': [
      'parameterValues',
      'isMaxMode',
      'isDefaultMaxConfig',
      'isDefaultNonMaxConfig',
      'variantStringRepresentation',
      'legacySlug',
    ],
    'aiserver.v1.AgentUrlConfig': ['agentUrl', 'agentnUrl'],
    'agent.v1.GetUsableModelsResponse': ['models'],
    'agent.v1.GetDefaultModelForCliResponse': ['model'],
    'agent.v1.ModelDetails': ['modelId', 'displayModelId', 'displayName', 'aliases', 'maxMode'],
    'agent.v1.AgentClientMessage': [
      'runRequest',
      'execClientMessage',
      'kvClientMessage',
      'clientHeartbeat',
    ],
    'agent.v1.AgentRunRequest': [
      'conversationState',
      'action',
      'requestedModel',
      'conversationId',
      'conversationGroupId',
      'mcpTools',
      'excludeWorkspaceContext',
      'selectedSubagentModels',
      'runId',
    ],
    'agent.v1.ConversationStateStructure': ['rootPromptMessagesJson', 'turns'],
    'agent.v1.ConversationTurnStructure': ['agentConversationTurn'],
    'agent.v1.AgentConversationTurnStructure': ['userMessage', 'steps'],
    'agent.v1.ConversationStep': ['assistantMessage', 'toolCall'],
    'agent.v1.AssistantMessage': ['text'],
    'agent.v1.ToolCall': [
      'shellToolCall',
      'grepToolCall',
      'readToolCall',
      'lsToolCall',
      'mcpToolCall',
      'toolCallId',
    ],
    'agent.v1.ShellToolCall': ['args'],
    'agent.v1.GrepToolCall': ['args'],
    'agent.v1.ReadToolCall': ['args'],
    'agent.v1.LsToolCall': ['args'],
    'agent.v1.ReadToolArgs': ['path', 'offset', 'limit', 'includeLineNumbers'],
    'agent.v1.McpToolCall': ['args', 'result'],
    'agent.v1.McpToolResult': ['success', 'error'],
    'agent.v1.McpResult': ['success', 'error'],
    'agent.v1.McpSuccess': ['content'],
    'agent.v1.McpError': ['error'],
    'agent.v1.McpToolError': ['error'],
    'agent.v1.McpToolResultContentItem': ['text'],
    'agent.v1.McpTextContent': ['text'],
    'agent.v1.ResumeAction': [],
    'agent.v1.ConversationAction': ['userMessageAction', 'resumeAction'],
    'agent.v1.UserMessageAction': ['userMessage'],
    'agent.v1.UserMessage': [
      'text',
      'messageId',
      'selectedContext',
      'mode',
      'conversationStateBlobId',
    ],
    'agent.v1.SelectedContext': '*',
    'agent.v1.McpTools': '*',
    'agent.v1.RequestedModel': [
      'modelId',
      'maxMode',
      'parameters',
      'builtInModel',
      'isVariantStringRepresentation',
    ],
    'agent.v1.RequestedModel.ModelParameterValue': ['id', 'value'],
    'agent.v1.ExecClientMessage': '*',
    'agent.v1.McpAllowlistPrecheckResult': ['allowlisted'],
    'agent.v1.McpStateExecResult': ['success'],
    'agent.v1.McpStateSuccess': ['servers'],
    'agent.v1.McpStateServer': ['serverName', 'serverIdentifier', 'tools', 'status'],
    'agent.v1.ListMcpResourcesExecResult': ['success'],
    'agent.v1.ListMcpResourcesSuccess': ['resources'],
    'agent.v1.RequestContextResult': ['success'],
    'agent.v1.RequestContextSuccess': ['requestContext'],
    'agent.v1.RequestContext': [
      'env',
      'tools',
      'webSearchEnabled',
      'webFetchEnabled',
      'supportsMcpAuth',
      'gitRepoInfoComplete',
      'mcpInfoComplete',
      'rulesInfoComplete',
      'envInfoComplete',
      'repositoryInfoComplete',
      'customSubagentsInfoComplete',
      'agentSkillsInfoComplete',
      'mcpFileSystemInfoComplete',
      'gitStatusInfoComplete',
      'searchConversationsEnabled',
      'sendMessageEnabled',
    ],
    'agent.v1.RequestContextEnv': '*',
    'agent.v1.McpToolDefinition': '*',
    'agent.v1.KvClientMessage': ['id', 'getBlobResult', 'setBlobResult'],
    'agent.v1.GetBlobResult': ['blobData'],
    'agent.v1.SetBlobResult': '*',
    'agent.v1.ClientHeartbeat': '*',
    'agent.v1.AgentServerMessage': ['interactionUpdate', 'execServerMessage', 'kvServerMessage'],
    'agent.v1.InteractionUpdate': [
      'textDelta',
      'toolCallStarted',
      'toolCallCompleted',
      'thinkingDelta',
      'partialToolCall',
      'tokenDelta',
      'turnEnded',
    ],
    'agent.v1.ToolCallStartedUpdate': ['callId', 'toolCall'],
    'agent.v1.ToolCallCompletedUpdate': ['callId', 'toolCall'],
    'agent.v1.PartialToolCallUpdate': ['callId', 'toolCall', 'argsTextDelta'],
    'agent.v1.TextDeltaUpdate': ['text'],
    'agent.v1.ThinkingDeltaUpdate': ['text'],
    'agent.v1.TokenDeltaUpdate': ['tokens'],
    'agent.v1.TurnEndedUpdate': '*',
    'agent.v1.ExecServerMessage': '*',
    'agent.v1.ReadArgs': ['path', 'toolCallId', 'offset', 'limit', 'encodingHint'],
    'agent.v1.ReadResult': ['success', 'rejected'],
    'agent.v1.ReadSuccess': '*',
    'agent.v1.ShellArgs': [
      'command',
      'workingDirectory',
      'timeout',
      'toolCallId',
      'simpleCommands',
      'isBackground',
      'description',
    ],
    'agent.v1.ShellResult': ['success', 'rejected'],
    'agent.v1.ShellSuccess': [
      'command',
      'workingDirectory',
      'exitCode',
      'stdout',
      'stderr',
      'interleavedOutput',
    ],
    'agent.v1.GrepArgs': [
      'pattern',
      'path',
      'glob',
      'outputMode',
      'caseInsensitive',
      'headLimit',
      'toolCallId',
      'offset',
    ],
    'agent.v1.GrepResult': ['success', 'error'],
    'agent.v1.GrepSuccess': ['pattern', 'path', 'outputMode', 'activeEditorResult'],
    'agent.v1.GrepUnionResult': ['content'],
    'agent.v1.GrepContentResult': ['matches', 'totalLines', 'totalMatchedLines'],
    'agent.v1.GrepFileMatch': ['file', 'matches'],
    'agent.v1.GrepContentMatch': ['lineNumber', 'content', 'contentTruncated', 'isContextLine'],
    'agent.v1.LsArgs': ['path', 'ignore', 'toolCallId', 'timeoutMs'],
    'agent.v1.LsResult': ['success', 'rejected'],
    'agent.v1.LsSuccess': ['directoryTreeRoot'],
    'agent.v1.LsDirectoryTreeNode': [
      'absPath',
      'childrenDirs',
      'childrenFiles',
      'childrenWereProcessed',
      'numFiles',
    ],
    'agent.v1.LsDirectoryTreeNode.File': ['name'],
    'agent.v1.WriteArgs': ['path', 'fileText', 'toolCallId'],
    'agent.v1.WriteResult': ['success', 'rejected'],
    'agent.v1.WriteSuccess': ['path', 'fileContentAfterWrite'],
    'agent.v1.DeleteArgs': ['path', 'toolCallId'],
    'agent.v1.DeleteResult': ['success', 'rejected'],
    'agent.v1.DeleteSuccess': ['path', 'deletedFile', 'prevContent'],
    'agent.v1.FetchArgs': ['url', 'toolCallId'],
    'agent.v1.FetchResult': ['success', 'error'],
    'agent.v1.FetchSuccess': ['url', 'content', 'statusCode'],
    'agent.v1.McpArgs': ['name', 'args', 'toolCallId', 'providerIdentifier', 'toolName'],
    'agent.v1.KvServerMessage': ['id', 'getBlobArgs', 'setBlobArgs'],
    'agent.v1.GetBlobArgs': ['blobId'],
    'agent.v1.SetBlobArgs': ['blobId', 'blobData'],
    'google.protobuf.Value': '*',
    'google.protobuf.Struct': '*',
    'google.protobuf.ListValue': '*',
  }),
);
